-- 1. SETUP ENVIRONMENT
CREATE OR REPLACE DATABASE HEALTH_INVENTORY_DB;
CREATE OR REPLACE SCHEMA HEALTH_INVENTORY_DB.PUBLIC;
CREATE OR REPLACE WAREHOUSE INVENTORY_WH WITH WAREHOUSE_SIZE = 'X-SMALL' AUTO_SUSPEND = 300;

-- 2. CREATE RAW DATA TABLE
CREATE OR REPLACE TABLE DAILY_STOCK_LOGS (
    LOG_DATE DATE,
    LOCATION_ID VARCHAR(50),
    ITEM_NAME VARCHAR(100),
    OPENING_STOCK INT,
    RECEIVED_QTY INT,
    ISSUED_QTY INT,
    CLOSING_STOCK INT,
    LEAD_TIME_DAYS INT
);

-- 3. SEED DUMMY DATA
INSERT INTO DAILY_STOCK_LOGS VALUES
('2023-10-01', 'General Hospital', 'Paracetamol', 1000, 0, 50, 950, 2),
('2023-10-02', 'General Hospital', 'Paracetamol', 950, 0, 60, 890, 2),
('2023-10-03', 'General Hospital', 'Paracetamol', 890, 0, 150, 740, 2),
('2023-10-01', 'Rural Clinic A', 'Insulin', 50, 0, 2, 48, 5),
('2023-10-02', 'Rural Clinic A', 'Insulin', 48, 0, 5, 43, 5),
('2023-10-03', 'Rural Clinic A', 'Insulin', 43, 0, 8, 35, 5),
('2023-10-01', 'City Warehouse', 'PPE Kits', 500, 200, 50, 650, 3),
('2023-10-02', 'City Warehouse', 'PPE Kits', 650, 0, 50, 600, 3),
('2023-10-03', 'City Warehouse', 'PPE Kits', 600, 0, 550, 50, 3);

-- 4. CREATE DYNAMIC TABLE (LOGIC)
CREATE OR REPLACE DYNAMIC TABLE INVENTORY_HEALTH_METRICS
TARGET_LAG = '1 minute'
WAREHOUSE = INVENTORY_WH
AS
WITH BASE_DATA AS (
    SELECT 
        LOCATION_ID,
        ITEM_NAME,
        MAX(LOG_DATE) as LAST_REPORT_DATE,
        MAX_BY(CLOSING_STOCK, LOG_DATE) as CURRENT_STOCK,
        ROUND(AVG(ISSUED_QTY), 1) as AVG_DAILY_USAGE,
        MAX(LEAD_TIME_DAYS) as LEAD_TIME
    FROM DAILY_STOCK_LOGS
    GROUP BY LOCATION_ID, ITEM_NAME
)
SELECT 
    *,
    CASE WHEN AVG_DAILY_USAGE = 0 THEN 999 ELSE ROUND(CURRENT_STOCK / AVG_DAILY_USAGE, 1) END as DAYS_REMAINING,
    CASE 
        WHEN (CASE WHEN AVG_DAILY_USAGE = 0 THEN 999 ELSE CURRENT_STOCK / AVG_DAILY_USAGE END) < LEAD_TIME THEN 'CRITICAL (Stockout Risk)'
        WHEN (CASE WHEN AVG_DAILY_USAGE = 0 THEN 999 ELSE CURRENT_STOCK / AVG_DAILY_USAGE END) < (LEAD_TIME * 2) THEN 'WARNING (Reorder Soon)'
        ELSE 'GOOD'
    END as STATUS,
    GREATEST(0, (AVG_DAILY_USAGE * 30) - CURRENT_STOCK) as SUGGESTED_REORDER_QTY
FROM BASE_DATA;
